CREATE TYPE "user_role" AS ENUM (
  'guest',
  'employee',
  'administrator'
);

CREATE TYPE "event_action" AS ENUM (
  'enter',
  'leave'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" user_role NOT NULL DEFAULT 'guest',
  "is_active" boolean NOT NULL DEFAULT true,
  "failed_attempts" int NOT NULL DEFAULT 0,
  "locked_until" timestamptz,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "room" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "art" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "artist" varchar(255),
  "price_cents" int,
  "image_path" varchar(500),
  "room_id" int
);

CREATE TABLE "gallery_event" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "room_id" int,
  "action" event_action NOT NULL,
  "occurred_at" timestamp NOT NULL DEFAULT (now()),
  "recorded_by" int
);

CREATE TABLE "audit_log" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" int,
  "action" varchar(100) NOT NULL,
  "target" varchar(255),
  "outcome" varchar(64) NOT NULL,
  "ip_address" varchar(45),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

-- Server-side sessions so a session can be revoked before it expires.
-- Only the SHA-256 of the token is stored, so a database leak cannot
-- be replayed as a live session cookie.
CREATE TABLE "sessions" (
  "session_hash" varchar(64) PRIMARY KEY,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp NOT NULL,
  "revoked" boolean NOT NULL DEFAULT false
);

ALTER TABLE "art" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gallery_event" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gallery_event" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gallery_event" ADD FOREIGN KEY ("recorded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_log" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "sessions_user_id_idx" ON "sessions" ("user_id");

CREATE INDEX "users_username_idx" ON "users" ("username");
